#pragma once
enum E_GAME_STATE
{
    GAME_READY = 0, GAME_PLAYING, GAME_PAUSE, GAME_CLEAR, GAME_OVER
};

enum E_PLAYER_STATE
{
    PLAYER_IDLE = 0, PLAYER_RUN, PLAYER_JUMP, PLAYER_DJUMP, PLAYER_END
};

enum E_EDGE
{
    EDGE_LEFT = 0, EDGE_TOP, EDGE_RIGHT, EDGE_BOTTOM, EDGE_END
};

enum E_SHAPE
{
    SHAPE_RECT = 0, SHAPE_CIRCLE, SHAPE_ELLIPSE, SHAPE_END
};

enum E_WEAPON_TYPE
{
    WEAPON_BULLET = 0, WEAPON_BUCKSHOT, WEAPON_TSAR, WEAPON_END
};

enum E_IMAGE_LOAD_KIND
{
    LOAD_EMPTY, LOAD_FILE, LOAD_END
};

enum E_ITEM_TYPE
{
    ITEM_SCORE = 0, ITEM_IMMORTAL, ITEM_MAGNET, ITEM_GIANT, ITEM_END
};